version: "3"
services:
  gdbui_server:
    build:
      dockerfile: DockerFile.dev
      context: ./gdbui_server
    volumes:
      - ./gdbui_server:/app
    ports:
      - "10000:10000"
    expose:
      - 10000

  webapp:
    build:
      dockerfile: DockerFile.dev
      context: ./webapp
    volumes:
      - /app/node_modules
      - ./webapp:/app
    ports:
      - "5173:5173"
    expose:
      - 5173
